import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { TRPCProvider } from "@/trpc/client";
import { ThemeProvider } from "@/providers/theme-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Upipe: Your own tube",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo-u-pipe.svg",
        href: "/logo-u-pipe.svg",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang={locale} suppressHydrationWarning>
        <body className={`${inter.className} dark:bg-[#191919]`}>
          <NextIntlClientProvider messages={messages}>
            <TRPCProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
                storageKey="u-pipe-theme"
              >
                <Toaster />
                {children}
              </ThemeProvider>
            </TRPCProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
